version: "3.9"

services:
  echo_api:
    build:
      context: ./ 
      dockerfile: API.Dockerfile 
    image: ts-api
    container_name: ts-api
    networks:
      - echo-net
    ports:
      - "9000:9000"
      - "9080:9080"
    volumes:
      - ./:/app 
      - credentials_volume:/root/.config/gcloud/ 
    stdin_open: false
    tty: true
    command: uvicorn app.main:app --host 0.0.0.0 --port 9000 --reload

networks:
  echo-net:
    driver: bridge

volumes:
  credentials_volume:
